<a href="https://colab.research.google.com/github/abdullah90ir/AI_booklet_CE-AUT/blob/master/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [87]:
#scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [88]:
scalar.ndim


0

In [89]:
#vector 
vector = torch.tensor([6,6])
vector

tensor([6, 6])

In [90]:
vector.ndim

1

In [91]:
vector.shape

torch.Size([2])

In [92]:
#matrix
matrix = torch.tensor([[4,5],
                      [4,8]])
matrix

tensor([[4, 5],
        [4, 8]])

In [93]:
matrix.ndim

2

In [94]:
matrix[0]

tensor([4, 5])

In [95]:
matrix.shape

torch.Size([2, 2])

In [96]:
#tendsor
tens = torch.tensor([[[1,2,8],
                      [5,4,9],
                      [5,3,7]]])
tens

tensor([[[1, 2, 8],
         [5, 4, 9],
         [5, 3, 7]]])

In [97]:
tens.ndim

3

In [98]:
tens.shape

torch.Size([1, 3, 3])

In [99]:
#random 
rand = torch.rand(3,4)
rand

tensor([[0.8964, 0.1595, 0.0377, 0.2455],
        [0.8397, 0.9063, 0.8970, 0.2459],
        [0.7250, 0.6529, 0.2734, 0.3842]])

In [100]:
rand.ndim

2

In [101]:
#random_tensor
rand_t = torch.rand(3,3,3)
rand_t


tensor([[[1.7476e-01, 1.9747e-01, 1.9815e-01],
         [3.1791e-01, 1.2218e-01, 4.3679e-01],
         [8.2375e-01, 3.5746e-01, 9.2544e-01]],

        [[2.6643e-05, 2.8939e-01, 3.2344e-01],
         [9.7265e-01, 6.9052e-01, 9.2893e-01],
         [4.6539e-01, 1.5008e-01, 2.5788e-01]],

        [[4.1753e-02, 4.1874e-01, 9.4083e-01],
         [9.2417e-01, 1.5060e-01, 5.6544e-01],
         [4.4443e-01, 9.5905e-02, 5.2497e-01]]])

In [102]:
rand_t.shape

torch.Size([3, 3, 3])

In [103]:
rand_t[2]


tensor([[0.0418, 0.4187, 0.9408],
        [0.9242, 0.1506, 0.5654],
        [0.4444, 0.0959, 0.5250]])

In [104]:
#range from number to another  with step
torch.arange(0 , 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
torch.arange(start=0 , end=100 , step=20)

tensor([ 0, 20, 40, 60, 80])

In [106]:
float_32_tensor = torch.tensor([3.0, 7.0, 9.0 ],
                               dtype=None, #data type for tensor must chosen correcty
                               device=None, #devices must chosen true on GPU or TPU or not
                               requires_grad=False)# whether or not to track gradiants on this tensor or not
float_32_tensor.dtype                            


torch.float32

In [107]:
#convert the tensors to another dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 7., 9.], dtype=torch.float16)

## tensors operatiopn
  ### -Addition
  ### -Subtractiong
  ### -Multiplication
  ### -Division
  ### -Matrix Multiplication




In [108]:
#crteat tensor 
tens = torch.tensor([1, 2, 4, 7])
tens + 10  #Add 10 to tensor

tensor([11, 12, 14, 17])

In [109]:
#multi. by 10
tens *10

tensor([10, 20, 40, 70])

In [110]:
#Sub. by 10
tens -10

tensor([-9, -8, -6, -3])

In [111]:
#matrix Multiplication{tensor * tensor}
print(f"The matrix multiplication : {tens * tens}")

The matrix multiplication : tensor([ 1,  4, 16, 49])


In [112]:
#nother way for matrix mul from torch 
torch.matmul(tens , tens)

tensor(70)

In [113]:
# to fix the shape or dim for matrix multiplication we need to make it transpose
#transpose make the matrix time we can use .T
tens_A = torch.tensor([[32, 51, 12],
                       [27, 0, 1]])

tens_B = torch.tensor([[2, 3, 4],
                       [5, 5, 9]])

In [114]:
torch.matmul(tens_A, tens_B)

RuntimeError: ignored

In [115]:
#as we seen the error about the shape (2x3 and 2x3) we need to transpose
#one of them to become correct (2x3 and 3x2)
#let transpose tens_B

tens_B.T , tens_B.T.shape

(tensor([[2, 5],
         [3, 5],
         [4, 9]]),
 torch.Size([3, 2]))

In [116]:
#Now let do it again (2x3 and 3x2) the result be (2x2)
torch.matmul(tens_A, tens_B.T)

tensor([[265, 523],
        [ 58, 144]])



### Finding Min , Max , Sum, Mean (aggregation)



In [117]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [118]:
#finding Min , Max
torch.min(x) , torch.max(x)

(tensor(1), tensor(91))

In [119]:
#finding the Mean 
torch.mean(x)

RuntimeError: ignored

In [120]:
#error wwith dtype
x.dtype

torch.int64

In [121]:
#let coorect it to 32 bit and after that take the Mean out
torch.mean(x.type(torch.float32))

tensor(46.)

In [122]:
#finding the sum of tensors
torch.sum(x)

tensor(460)

In [123]:
#Let find the index locations of aggregation
#let find the location of min , max 
x.argmin() , x.argmax(), x

(tensor(0), tensor(9), tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]))

In [124]:
x[0] , x[9]

(tensor(1), tensor(91))

#### Reshaping , stacking , squeezing , unsqueezing

In [125]:
z = torch.arange(0. , 10.)
z, z.shape

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([10]))

In [126]:
#Adding extra dimintion
z_reshape = z.reshape(10 , 1)
z_reshape , z_reshape.shape

(tensor([[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([10, 1]))

In [127]:
#change the view with the same elements 
z_reshape = z.reshape(5 , 2)
z_reshape , z_reshape.shape

(tensor([[0., 1.],
         [2., 3.],
         [4., 5.],
         [6., 7.],
         [8., 9.]]),
 torch.Size([5, 2]))

In [133]:
#another change view by 
y = z.view(1,10)
y

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [139]:
#stack the tensor on the top of eachother dim 1 changing virtical or horizantal
x_stack = torch.stack([z,z,z,z,z],dim=1)
x_stack

tensor([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8.],
        [9., 9., 9., 9., 9.]])

In [157]:
#squeeze  can useing the function of torch.squeeze() the dim from 2dim to single dim
y.squeeze(0).shape

torch.Size([10])

In [165]:
y.unsqueeze(0).shape

torch.Size([1, 1, 10])

In [167]:
#permute rearrange the dim of tensors le test 
k_orginal = torch.rand(224, 224, 3)#image shape (hight,width,color channel)

k_permute = k_orginal.permute(2, 0, 1)#rearrange image(3, 224, 224)
k_permute

tensor([[[0.3337, 0.4979, 0.3855,  ..., 0.4544, 0.0954, 0.4948],
         [0.8889, 0.8386, 0.0531,  ..., 0.2035, 0.7886, 0.6656],
         [0.0241, 0.4775, 0.0340,  ..., 0.5523, 0.8633, 0.1067],
         ...,
         [0.6897, 0.5044, 0.7362,  ..., 0.4811, 0.0050, 0.7258],
         [0.8486, 0.9421, 0.5485,  ..., 0.1749, 0.7414, 0.6847],
         [0.0232, 0.2707, 0.1829,  ..., 0.3487, 0.3294, 0.5998]],

        [[0.9590, 0.8918, 0.4176,  ..., 0.6574, 0.1641, 0.6716],
         [0.4911, 0.4880, 0.2955,  ..., 0.5824, 0.7055, 0.8556],
         [0.0447, 0.7779, 0.3782,  ..., 0.9606, 0.2304, 0.3000],
         ...,
         [0.2529, 0.5356, 0.8028,  ..., 0.8889, 0.2059, 0.6577],
         [0.8434, 0.1785, 0.6900,  ..., 0.5944, 0.7017, 0.6271],
         [0.9417, 0.3582, 0.9332,  ..., 0.3675, 0.0373, 0.2958]],

        [[0.0064, 0.1968, 0.9484,  ..., 0.7793, 0.6534, 0.2577],
         [0.7004, 0.5824, 0.5893,  ..., 0.2309, 0.3283, 0.1896],
         [0.3657, 0.1041, 0.8165,  ..., 0.5357, 0.1227, 0.

In [169]:
k_orginal.shape ,k_permute.shape 

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [174]:
#selecting data from tensors (its similar like numpy)
idx = torch.arange(1,10).reshape(1 , 3, 3)
idx

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [175]:
idx[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [177]:
#index first bracket
idx[0][0]

tensor([1, 2, 3])

In [184]:
#index first element from first bracket
idx[0][0][0] , idx[0][2][2]

(tensor(1), tensor(9))

In [186]:
  #index all of target by ": "
idx[:,0]

tensor([[1, 2, 3]])

In [190]:
#index all of 0th and 1st dim but only index 1 of 2nd dim
idx[:, :, 1]

tensor([[2, 5, 8]])

In [194]:
#all of the 0th dim but only 1 index value of 1st and 2nd dim 
idx[:, 1,1] , idx[:, 1,2]

(tensor([5]), tensor([6]))

### numpy and tensor in pytorch

In [199]:
array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)#changing from numpy to tensor
array , tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [200]:
array.dtype , tensor.dtype

(dtype('float64'), torch.float64)

In [202]:
#changing from tesor to numpy {  tensor.torch.numpy()  }
tt = torch.ones(7)
arr = tt.numpy()
tt , arr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [205]:
tt.dtype , arr.dtype #just cheack the data type when changing to avoid the errors

(torch.float32, dtype('float32'))

#### repreduceble random اعاده تولید نفس الارقام العشوائيه

#### reproudect the same random number by using SEED

In [208]:
#random seed to prodect same number
rand_seed = 43
torch.manual_seed(rand_seed)
tens1 = torch.rand(3, 4)

torch.manual_seed(rand_seed)#we have to use it evrytime on tensor
tens2 = torch.rand(3, 4)

print(tens1)
print(tens1 == tens2)
print(tens2)

#we proudect the same random number

tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
tensor([[0.4540, 0.1965, 0.9210, 0.3462],
        [0.1481, 0.0858, 0.5909, 0.0659],
        [0.7476, 0.6253, 0.9392, 0.1338]])
